Fixed bug in hook

diff --git a/shared_hooks/pre-commit b/shared_hooks/pre-commit
--- a/shared_hooks/pre-commit
+++ b/shared_hooks/pre-commit
@@ -11,7 +11,9 @@
 
 NBS=$(echo $(git diff --full-index -z --cached $against --name-only) | sort | grep "ipynb")
 
-[[ -z "$NBS" ]] || command -v nbstripout >/dev/null 2>&1 || { echo >&2 "I require nbstripout but it's not installed. Aborting commit."; exit 1; }
+if [ ! -z "$NBS" ] ; then
+	command -v nbstripout >/dev/null 2>&1 || { echo >&2 "I require nbstripout but it's not installed. Aborting commit."; exit 1; }
+fi
 
 for NB in $NBS ; do
     echo "Removing outputs from $NB"
